In [46]:
import os
os.environ['OMP_NUM_THREADS'] = '4'
os.environ['MKL_NUM_THREADS'] = '4'
os.environ['OPENBLAS_NUM_THREADS'] = '4'

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from typing import List, Optional, Union, Dict, Tuple
from tqdm.autonotebook import tqdm
import warnings
warnings.filterwarnings('ignore')

# HOUSTON

## XGBoost

In [152]:
def short_term_forecast_XGB(hour=None):
    # 模型配置（当前最佳）
    model = XGBRegressor(
        n_estimators=1000,
        max_depth=6,
        learning_rate=0.01,
        subsample=0.8,
        colsample_bytree=0.8,
        colsample_bylevel=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        min_child_weight=10,
        gamma=0,
        objective='reg:absoluteerror',
        tree_method='gpu_hist',
        # enable_categorical=True,
        random_state=42,
        n_joba=-1,
        verbosity=0,
    )

    X = pd.read_csv('./train_data/dam_features.csv')
    if hour:
        X = X[X.hour==hour]
        _ = X.pop('hour')
    X = X[X.timestamp >= '2022-01-01 00:00:00']
    print(X.shape)
    X.replace([np.inf, -np.inf], np.nan, inplace=True)
    X = X.dropna()
    X_train = X[X.timestamp < '2025-01-01 00:00:00']
    X_test = X[X.timestamp >= '2025-01-01 00:00:00']
    _ = X_train.pop('timestamp')
    dt = X_test.pop('timestamp')
    y_train = X_train.pop('target')
    y_test = X_test.pop('target')

    if hour:
        cat_features = [0, 1, 2, 3, 5, 6, 7, 8, 31, 32]
    else:
        cat_features = [0, 1, 2, 3, 4, 6, 7, 8, 9, 32, 33]

    # for i in cat_features:
    #     X_train.iloc[:, i] = X_train.iloc[:, i].astype("category")
    #     X_test.iloc[:, i] = X_test.iloc[:, i].astype("category")

    model.fit(
        X_train, y_train
    )
    
    return  model, X_test, y_test, dt

### 01:00 - 24:00

In [153]:
preds = []
y_tests = []
for h in tqdm(range(1, 25)):
    print("************************")
    print(f'开始第{h}小时预测')
    print("************************")
    model1, X_test, y_test, dt = short_term_forecast_XGB(hour=h)

    y_pred = model1.predict(X_test)
    xgb_model_mae1 = mean_absolute_error(y_test, y_pred)
    xgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
    native_mae1 = mean_absolute_error(y_test, X_test['dam_lag_24h'])
    native_rmse1 = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
    print("xgb_model_mae1:", round(xgb_model_mae1, 2))
    print("native_mae:", round(native_mae1, 2))

    print("xgb_model_rmse1:", round(xgb_model_rmse1
                                    , 2))
    print("native_rmse:", round(native_rmse1, 2))

    xgb_mae_enhance1 = round((native_mae1 - xgb_model_mae1) / native_mae1 * 100, 2)
    xgb_rmse_enhance1 = round((native_rmse1 - xgb_model_rmse1) / native_rmse1 * 100, 2)
    print('mae 提升:', xgb_mae_enhance1, '%')
    print('rmse 提升:', xgb_rmse_enhance1, '%')
    preds.extend(list(y_pred))
    y_tests.extend(list(y_test))
    print()

  0%|          | 0/24 [00:00<?, ?it/s]

************************
开始第1小时预测
************************
(1431, 36)
xgb_model_mae1: 5.07
native_mae: 7.01
xgb_model_rmse1: 7.82
native_rmse: 10.53
mae 提升: 27.73 %
rmse 提升: 25.7 %

************************
开始第2小时预测
************************
(1431, 36)
xgb_model_mae1: 4.82
native_mae: 6.12
xgb_model_rmse1: 7.25
native_rmse: 9.21
mae 提升: 21.18 %
rmse 提升: 21.24 %

************************
开始第3小时预测
************************
(1427, 36)
xgb_model_mae1: 5.01
native_mae: 5.96
xgb_model_rmse1: 7.59
native_rmse: 9.16
mae 提升: 15.82 %
rmse 提升: 17.16 %

************************
开始第4小时预测
************************
(1431, 36)
xgb_model_mae1: 5.07
native_mae: 5.97
xgb_model_rmse1: 7.68
native_rmse: 9.13
mae 提升: 15.13 %
rmse 提升: 15.87 %

************************
开始第5小时预测
************************
(1431, 36)
xgb_model_mae1: 5.03
native_mae: 6.39
xgb_model_rmse1: 8.11
native_rmse: 9.89
mae 提升: 21.23 %
rmse 提升: 17.99 %

************************
开始第6小时预测
************************
(1431, 36)
xgb_model_mae1: 6.27
native_mae: 8.14
xgb_model_rmse1: 13.16
native_rmse: 16.17
mae 提升: 23.01 %
rmse 提升: 18.62 %

************************
开始第7小时预测
************************
(1431, 36)
xgb_model_mae1: 9.17
native_mae: 13.43
xgb_model_rmse1: 41.06
native_rmse: 53.82
mae 提升: 31.74 %
rmse 提升: 23.71 %

************************
开始第8小时预测
************************
(1431, 36)
xgb_model_mae1: 9.24
native_mae: 13.46
xgb_model_rmse1: 41.36
native_rmse: 52.85
mae 提升: 31.35 %
rmse 提升: 21.74 %

************************
开始第9小时预测
************************
(1431, 36)
xgb_model_mae1: 5.9
native_mae: 7.56
xgb_model_rmse1: 12.76
native_rmse: 15.36
mae 提升: 21.87 %
rmse 提升: 16.9 %

************************
开始第10小时预测
************************
(1431, 36)
xgb_model_mae1: 5.42
native_mae: 6.38
xgb_model_rmse1: 8.28
native_rmse: 9.73
mae 提升: 15.11 %
rmse 提升: 14.89 %

************************
开始第11小时预测
************************
(1431, 36)
xgb_model_mae1: 5.25
native_mae: 6.14
xgb_model_rmse1: 7.65
native_rmse: 8.99
mae 提升: 14.53 %
rmse 提升: 14.94 %

************************
开始第12小时预测
************************
(1431, 36)
xgb_model_mae1: 5.22
native_mae: 6.11
xgb_model_rmse1: 7.07
native_rmse: 8.5
mae 提升: 14.57 %
rmse 提升: 16.92 %

************************
开始第13小时预测
************************
(1431, 36)
xgb_model_mae1: 5.73
native_mae: 6.6
xgb_model_rmse1: 7.55
native_rmse: 9.05
mae 提升: 13.2 %
rmse 提升: 16.54 %

************************
开始第14小时预测
************************
(1431, 36)
xgb_model_mae1: 6.63
native_mae: 7.7
xgb_model_rmse1: 8.84
native_rmse: 10.5
mae 提升: 13.93 %
rmse 提升: 15.78 %

************************
开始第15小时预测
************************
(1431, 36)
xgb_model_mae1: 7.44
native_mae: 8.35
xgb_model_rmse1: 10.34
native_rmse: 11.63
mae 提升: 10.93 %
rmse 提升: 11.05 %

************************
开始第16小时预测
************************
(1431, 36)
xgb_model_mae1: 8.08
native_mae: 9.21
xgb_model_rmse1: 12.19
native_rmse: 13.02
mae 提升: 12.24 %
rmse 提升: 6.42 %

************************
开始第17小时预测
************************
(1431, 36)
xgb_model_mae1: 9.31
native_mae: 10.4
xgb_model_rmse1: 14.22
native_rmse: 15.12
mae 提升: 10.48 %
rmse 提升: 5.94 %

************************
开始第18小时预测
************************
(1431, 36)
xgb_model_mae1: 11.33
native_mae: 13.57
xgb_model_rmse1: 17.45
native_rmse: 21.1
mae 提升: 16.45 %
rmse 提升: 17.31 %

************************
开始第19小时预测
************************
(1431, 36)
xgb_model_mae1: 15.32
native_mae: 17.63
xgb_model_rmse1: 23.37
native_rmse: 28.14
mae 提升: 13.06 %
rmse 提升: 16.96 %

************************
开始第20小时预测
************************
(1431, 36)
xgb_model_mae1: 23.48
native_mae: 27.33
xgb_model_rmse1: 47.02
native_rmse: 56.22
mae 提升: 14.08 %
rmse 提升: 16.36 %

************************
开始第21小时预测
************************
(1431, 36)
xgb_model_mae1: 20.73
native_mae: 25.53
xgb_model_rmse1: 43.24
native_rmse: 54.6
mae 提升: 18.79 %
rmse 提升: 20.82 %

************************
开始第22小时预测
************************
(1431, 36)
xgb_model_mae1: 14.09
native_mae: 17.37
xgb_model_rmse1: 28.66
native_rmse: 33.87
mae 提升: 18.9 %
rmse 提升: 15.38 %

************************
开始第23小时预测
************************
(1431, 36)
xgb_model_mae1: 8.64
native_mae: 10.37
xgb_model_rmse1: 13.39
native_rmse: 15.53
mae 提升: 16.72 %
rmse 提升: 13.75 %

************************
开始第24小时预测
************************
(1431, 36)
xgb_model_mae1: 6.34
native_mae: 7.12
xgb_model_rmse1: 9.21
native_rmse: 10.4
mae 提升: 11.06 %
rmse 提升: 11.47 %

In [17]:
y_pred = preds
y_test = y_tests
xgb_model_mae1 = mean_absolute_error(y_test, y_pred)
xgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
print("xgb_model_mae1:", xgb_model_mae1)

print("xgb_model_rmse1:", xgb_model_rmse1)

xgb_model_mae1: 8.800295213523574
xgb_model_rmse1: 21.17635063357332

In [154]:
model1, X_test, y_test, dt = short_term_forecast_XGB()

y_pred = model1.predict(X_test)
xgb_model_mae1 = mean_absolute_error(y_test, y_pred)
xgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
native_mae1 = mean_absolute_error(y_test, X_test['dam_lag_24h'])
native_rmse1 = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
print("xgb_model_mae1:", xgb_model_mae1)
print("native_mae:", native_mae1)

print("xgb_model_rmse1:", xgb_model_rmse1)
print("native_rmse:", native_rmse1)

xgb_mae_enhance1 = round((native_mae1 - xgb_model_mae1) / native_mae1 * 100, 2)
xgb_rmse_enhance1 = round((native_rmse1 - xgb_model_rmse1) / native_rmse1 * 100, 2)
print('mae 提升:', xgb_mae_enhance1, '%')
print('rmse 提升:', xgb_rmse_enhance1, '%')

(34340, 37)
xgb_model_mae1: 8.604912286374715
native_mae: 10.578265705206551
xgb_model_rmse1: 20.853778189985533
native_rmse: 26.220882300682653
mae 提升: 18.65 %
rmse 提升: 20.47 %

In [155]:
xgb_pre = model1.predict(X_test)

### test

In [156]:
X = pd.read_csv('./train_data/dam_features.csv')
X_test = X[X.timestamp >= '2025-01-01 00:00:00']
X_test = X_test.dropna()

In [157]:
y_pred = pd.Series(y_pred)
y_test.reset_index(drop=True, inplace=True)
dt = X_test[['timestamp', 'hour']]
dt.reset_index(drop=True, inplace=True)
result = pd.concat([dt, y_test, y_pred], axis=1)
result.columns = ['dt', 'hour', 'target', 'pred']

In [158]:
result.to_csv("DAM_result.csv", index=None)

In [159]:
result

                       dt  hour  target       pred
0     2025-01-01 06:00:00     1   20.14  19.958693
1     2025-01-01 06:00:00     2   17.90  19.083134
2     2025-01-01 06:00:00     3   16.69  18.180393
3     2025-01-01 06:00:00     4   17.02  17.618713
4     2025-01-01 06:00:00     5   18.21  18.464663
...                   ...   ...     ...        ...
8177  2025-12-09 06:00:00    20   60.05  37.721817
8178  2025-12-09 06:00:00    21   63.34  36.119938
8179  2025-12-09 06:00:00    22   57.15  33.842979
8180  2025-12-09 06:00:00    23   49.72  29.196398
8181  2025-12-09 06:00:00    24   43.61  27.514921

[8182 rows x 4 columns]

## LightGBM

In [197]:
def short_term_forecast_LGBM(hour=None):
    # 模型配置（当前最佳）
    model = LGBMRegressor(
        n_estimators=1000,
        num_leaves=31,
        max_depth=8,
        learning_rate=0.01,
        subsample=0.8,
        colsample_bytree=0.8,
        subsample_freq=1,
        reg_alpha=0.1,
        reg_lambda=1.0,
        min_child_samples=20,
        min_child_weight=1e-3,
        objective='mae',
        metric='mae',
        device='gpu',
        boosting_type='gbdt',
        random_state=42,
        n_jobs=4,
        verbose=-1,
        force_row_wise=True,
    )

    X = pd.read_csv('./train_data/dam_features.csv')
    if hour:
        X = X[X.hour==hour]
        _ = X.pop('hour')
    X = X[X.timestamp >= '2022-01-01 00:00:00']
    print(X.shape)
    X.replace([np.inf, -np.inf], np.nan, inplace=True)
    X = X.dropna()
    X_train = X[X.timestamp < '2025-01-01 00:00:00']
    X_test = X[X.timestamp >= '2025-01-01 00:00:00']
    _ = X_train.pop('timestamp')
    dt = X_test.pop('timestamp')
    y_train = X_train.pop('target')
    y_test = X_test.pop('target')

    if hour:
        cat_features = [0, 1, 2, 3, 5, 6, 7, 8, 31, 32]
    else:
        cat_features = [0, 1, 2, 3, 4, 6, 7, 8, 9, 32, 33]

    # for i in cat_features:
    #     X_train.iloc[:, i] = X_train.iloc[:, i].astype("category")
    #     X_test.iloc[:, i] = X_test.iloc[:, i].astype("category")

    model.fit(
        X_train, y_train,
        # categorical_feature=cat_features
    )
    
    return  model, X_test, y_test, dt

### 01:00 - 24:00

In [161]:
preds = []
y_tests = []
for h in tqdm(range(1, 25)):
    print("************************")
    print(f'开始第{h}小时预测')
    print("************************")
    model1, X_test, y_test, dt = short_term_forecast_LGBM(hour=h)

    y_pred = model1.predict(X_test)
    lgb_model_mae1 = mean_absolute_error(y_test, y_pred)
    lgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
    native_mae = mean_absolute_error(y_test, X_test['dam_lag_24h'])
    native_rmse = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
    print("lgb_model_mae1:", lgb_model_mae1)
    print("native_mae:", native_mae)

    print("lgb_model_rmse1:", lgb_model_rmse1)
    print("native_rmse:", native_rmse)

    lgb_mae_enhance1 = round((native_mae - lgb_model_mae1) / native_mae * 100, 2)
    lgb_rmse_enhance1 = round((native_rmse - lgb_model_rmse1) / native_rmse * 100, 2)
    print('mae 提升:', lgb_mae_enhance1, '%')
    print('rmse 提升:', lgb_rmse_enhance1, '%')
    preds.extend(list(y_pred))
    y_tests.extend(list(y_test))
    print()

  0%|          | 0/24 [00:00<?, ?it/s]

************************
开始第1小时预测
************************
(1431, 36)
lgb_model_mae1: 5.205485948764017
native_mae: 7.0146627565982405
lgb_model_rmse1: 8.180345974777522
native_rmse: 10.530246395481928
mae 提升: 25.79 %
rmse 提升: 22.32 %

************************
开始第2小时预测
************************
(1431, 36)
lgb_model_mae1: 5.068310956320296
native_mae: 6.117096774193548
lgb_model_rmse1: 7.66545171317349
native_rmse: 9.208141415532548
mae 提升: 17.15 %
rmse 提升: 16.75 %

************************
开始第3小时预测
************************
(1427, 36)
lgb_model_mae1: 5.347034396758856
native_mae: 5.956755162241889
lgb_model_rmse1: 8.07457067632227
native_rmse: 9.160040930722273
mae 提升: 10.24 %
rmse 提升: 11.85 %

************************
开始第4小时预测
************************
(1431, 36)
lgb_model_mae1: 5.275584020205186
native_mae: 5.972815249266862
lgb_model_rmse1: 8.020753728330835
native_rmse: 9.126912011951266
mae 提升: 11.67 %
rmse 提升: 12.12 %

************************
开始第5小时预测
************************
(1431, 36)
lgb_model_mae1: 5.312989338011083
native_mae: 6.385894428152493
lgb_model_rmse1: 8.531771180977062
native_rmse: 9.886455781415732
mae 提升: 16.8 %
rmse 提升: 13.7 %

************************
开始第6小时预测
************************
(1431, 36)
lgb_model_mae1: 6.270728465523395
native_mae: 8.143782991202345
lgb_model_rmse1: 13.512319386827038
native_rmse: 16.166565303871447
mae 提升: 23.0 %
rmse 提升: 16.42 %

************************
开始第7小时预测
************************
(1431, 36)
lgb_model_mae1: 9.645596466618283
native_mae: 13.43222873900293
lgb_model_rmse1: 42.27388773504666
native_rmse: 53.82472041326348
mae 提升: 28.19 %
rmse 提升: 21.46 %

************************
开始第8小时预测
************************
(1431, 36)
lgb_model_mae1: 9.707514819714083
native_mae: 13.457272727272729
lgb_model_rmse1: 42.524646601203195
native_rmse: 52.84917242587348
mae 提升: 27.86 %
rmse 提升: 19.54 %

************************
开始第9小时预测
************************
(1431, 36)
lgb_model_mae1: 6.094844780700527
native_mae: 7.555777126099707
lgb_model_rmse1: 13.478012051089275
native_rmse: 15.359643736704152
mae 提升: 19.34 %
rmse 提升: 12.25 %

************************
开始第10小时预测
************************
(1431, 36)
lgb_model_mae1: 5.51166674791609
native_mae: 6.381935483870967
lgb_model_rmse1: 8.46271200316763
native_rmse: 9.727253035307719
mae 提升: 13.64 %
rmse 提升: 13.0 %

************************
开始第11小时预测
************************
(1431, 36)
lgb_model_mae1: 5.327607110993588
native_mae: 6.143372434017596
lgb_model_rmse1: 7.724134577750496
native_rmse: 8.989072789713537
mae 提升: 13.28 %
rmse 提升: 14.07 %

************************
开始第12小时预测
************************
(1431, 36)
lgb_model_mae1: 5.2048114704316895
native_mae: 6.110146627565983
lgb_model_rmse1: 7.049841700709047
native_rmse: 8.503378455725132
mae 提升: 14.82 %
rmse 提升: 17.09 %

************************
开始第13小时预测
************************
(1431, 36)
lgb_model_mae1: 5.821453772802812
native_mae: 6.598709677419355
lgb_model_rmse1: 7.612934564309583
native_rmse: 9.052369725876144
mae 提升: 11.78 %
rmse 提升: 15.9 %

************************
开始第14小时预测
************************
(1431, 36)
lgb_model_mae1: 6.5918666871809775
native_mae: 7.699384164222875
lgb_model_rmse1: 8.890151259770873
native_rmse: 10.497624099300054
mae 提升: 14.38 %
rmse 提升: 15.31 %

************************
开始第15小时预测
************************
(1431, 36)
lgb_model_mae1: 7.369151623434096
native_mae: 8.35041055718475
lgb_model_rmse1: 10.21114578977232
native_rmse: 11.630062534030268
mae 提升: 11.75 %
rmse 提升: 12.2 %

************************
开始第16小时预测
************************
(1431, 36)
lgb_model_mae1: 8.276399546175671
native_mae: 9.210322580645162
lgb_model_rmse1: 11.967588775189762
native_rmse: 13.024616733544157
mae 提升: 10.14 %
rmse 提升: 8.12 %

************************
开始第17小时预测
************************
(1431, 36)
lgb_model_mae1: 9.199914671748477
native_mae: 10.397126099706744
lgb_model_rmse1: 14.641180368441647
native_rmse: 15.118252819967184
mae 提升: 11.51 %
rmse 提升: 3.16 %

************************
开始第18小时预测
************************
(1431, 36)
lgb_model_mae1: 11.597987135970554
native_mae: 13.56565982404692
lgb_model_rmse1: 18.663928485403762
native_rmse: 21.0999382009074
mae 提升: 14.5 %
rmse 提升: 11.55 %

************************
开始第19小时预测
************************
(1431, 36)
lgb_model_mae1: 15.021682396898125
native_mae: 17.625219941348977
lgb_model_rmse1: 24.477362833286293
native_rmse: 28.14372975176133
mae 提升: 14.77 %
rmse 提升: 13.03 %

************************
开始第20小时预测
************************
(1431, 36)
lgb_model_mae1: 22.557540334578643
native_mae: 27.329794721407623
lgb_model_rmse1: 45.32764961364245
native_rmse: 56.21990567004171
mae 提升: 17.46 %
rmse 提升: 19.37 %

************************
开始第21小时预测
************************
(1431, 36)
lgb_model_mae1: 20.202757897232598
native_mae: 25.52944281524927
lgb_model_rmse1: 43.207900902470904
native_rmse: 54.60265172467881
mae 提升: 20.86 %
rmse 提升: 20.87 %

************************
开始第22小时预测
************************
(1431, 36)
lgb_model_mae1: 14.135613493370201
native_mae: 17.374780058651023
lgb_model_rmse1: 28.601853536961755
native_rmse: 33.8725738069162
mae 提升: 18.64 %
rmse 提升: 15.56 %

************************
开始第23小时预测
************************
(1431, 36)
lgb_model_mae1: 8.872601017345543
native_mae: 10.374721407624632
lgb_model_rmse1: 13.529871727408286
native_rmse: 15.52517869807102
mae 提升: 14.48 %
rmse 提升: 12.85 %

************************
开始第24小时预测
************************
(1431, 36)
lgb_model_mae1: 6.557032455764797
native_mae: 7.123958944281523
lgb_model_rmse1: 9.49345218565584
native_rmse: 10.39863975708621
mae 提升: 7.96 %
rmse 提升: 8.7 %

In [162]:
y_pred = preds
y_test = y_tests
xgb_model_mae1 = mean_absolute_error(y_test, y_pred)
xgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
print("lgb_model_mae1:", xgb_model_mae1)

print("lgb_model_rmse1:", xgb_model_rmse1)

lgb_model_mae1: 8.75817425999477
lgb_model_rmse1: 21.43795010916479

In [203]:
model1, X_test, y_test, dt = short_term_forecast_LGBM()

y_pred = model1.predict(X_test)
lgb_model_mae1 = mean_absolute_error(y_test, y_pred)
lgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
native_mae = mean_absolute_error(y_test, X_test['dam_lag_24h'])
native_rmse = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
print("lgb_model_mae1:", lgb_model_mae1)
print("native_mae:", native_mae)

print("lgb_model_rmse1:", lgb_model_rmse1)
print("native_rmse:", native_rmse)

lgb_mae_enhance1 = round((native_mae - lgb_model_mae1) / native_mae * 100, 2)
lgb_rmse_enhance1 = round((native_rmse - lgb_model_rmse1) / native_rmse * 100, 2)
print('mae 提升:', lgb_mae_enhance1, '%')
print('rmse 提升:', lgb_rmse_enhance1, '%')

(34340, 37)
lgb_model_mae1: 8.570603826465518
native_mae: 10.578265705206551
lgb_model_rmse1: 20.80648641232052
native_rmse: 26.220882300682653
mae 提升: 18.98 %
rmse 提升: 20.65 %

In [204]:
lgb_pre = model1.predict(X_test)

### test

In [205]:
X = pd.read_csv('./train_data/dam_features.csv')
X_test = X[X.timestamp >= '2025-01-01 00:00:00']
X_test = X_test.dropna()

In [206]:
y_pred = pd.Series(y_pred)
y_test.reset_index(drop=True, inplace=True)
dt = X_test[['timestamp', 'hour']]
dt.reset_index(drop=True, inplace=True)
result = pd.concat([dt, y_test, y_pred], axis=1)
result.columns = ['dt', 'hour', 'target', 'pred']

In [207]:
result.to_csv("LGBM_DAM_result.csv", index=None)

In [208]:
result

                       dt  hour  target       pred
0     2025-01-01 06:00:00     1   20.14  19.753001
1     2025-01-01 06:00:00     2   17.90  19.074642
2     2025-01-01 06:00:00     3   16.69  18.640579
3     2025-01-01 06:00:00     4   17.02  17.960322
4     2025-01-01 06:00:00     5   18.21  19.093189
...                   ...   ...     ...        ...
8177  2025-12-09 06:00:00    20   60.05  37.727234
8178  2025-12-09 06:00:00    21   63.34  36.967250
8179  2025-12-09 06:00:00    22   57.15  34.352606
8180  2025-12-09 06:00:00    23   49.72  30.498739
8181  2025-12-09 06:00:00    24   43.61  28.096883

[8182 rows x 4 columns]

## CatBoost

In [169]:
def short_term_forecast_CAT(hour=None):
    # 模型配置（当前最佳）
    if hour:
        cat_features = [0, 1, 2, 3, 5, 6, 7, 8, 31, 32]
    else:
        cat_features = [0, 1, 2, 3, 4, 6, 7, 8, 9, 32, 33]
    model = CatBoostRegressor(
        iterations=2000,
        depth=6,
        learning_rate=0.2,
        l2_leaf_reg=3.0,
        random_strength=1.0,
        min_data_in_leaf=20,
        subsample=0.8,
        bootstrap_type='Bernoulli',
        loss_function='MAE',
        task_type='GPU',
        random_seed=42,
        thread_count=-1,
        verbose=0,
        allow_writing_files=False,
        # cat_features=cat_features,
    )
    

    X = pd.read_csv('./train_data/dam_features.csv')
    if hour:
        X = X[X.hour==hour]
        _ = X.pop('hour')
    X = X[X.timestamp >= '2022-01-01 00:00:00']
    print(X.shape)
    X.replace([np.inf, -np.inf], np.nan, inplace=True)
    X = X.dropna()
    X_train = X[X.timestamp < '2025-01-01 00:00:00']
    X_test = X[X.timestamp >= '2025-01-01 00:00:00']
    _ = X_train.pop('timestamp')
    dt = X_test.pop('timestamp')
    y_train = X_train.pop('target')
    y_test = X_test.pop('target')

    # for i in cat_features:
    #     X_train.iloc[:, i] = X_train.iloc[:, i].astype("category")
    #     X_test.iloc[:, i] = X_test.iloc[:, i].astype("category")

    model.fit(
        X_train, y_train
    )
    
    return  model, X_test, y_test, dt

### 01:00 - 24:00

In [170]:
preds = []
y_tests = []
for h in tqdm(range(1, 25)):
    print("************************")
    print(f'开始第{h}小时预测')
    print("************************")
    model1, X_test, y_test, dt = short_term_forecast_CAT(hour=h)

    y_pred = model1.predict(X_test)
    cat_model_mae1 = mean_absolute_error(y_test, y_pred)
    cat_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
    native_mae = mean_absolute_error(y_test, X_test['dam_lag_24h'])
    native_rmse = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
    print("lgb_model_mae1:", cat_model_mae1)
    print("native_mae:", native_mae)

    print("lgb_model_rmse1:", cat_model_rmse1)
    print("native_rmse:", native_rmse)

    cat_mae_enhance1 = round((native_mae - cat_model_mae1) / native_mae * 100, 2)
    cat_rmse_enhance1 = round((native_rmse - cat_model_rmse1) / native_rmse * 100, 2)
    print('mae 提升:', cat_mae_enhance1, '%')
    print('rmse 提升:', cat_rmse_enhance1, '%')
    preds.extend(list(y_pred))
    y_tests.extend(list(y_test))
    print()

  0%|          | 0/24 [00:00<?, ?it/s]

************************
开始第1小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.05104557150313
native_mae: 7.0146627565982405
lgb_model_rmse1: 7.6588235447636315
native_rmse: 10.530246395481928
mae 提升: 27.99 %
rmse 提升: 27.27 %

************************
开始第2小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 4.87901785392338
native_mae: 6.117096774193548
lgb_model_rmse1: 7.338657405685829
native_rmse: 9.208141415532548
mae 提升: 20.24 %
rmse 提升: 20.3 %

************************
开始第3小时预测
************************
(1427, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.526508479128981
native_mae: 5.956755162241889
lgb_model_rmse1: 8.127744166327775
native_rmse: 9.160040930722273
mae 提升: 7.22 %
rmse 提升: 11.27 %

************************
开始第4小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.344342578395309
native_mae: 5.972815249266862
lgb_model_rmse1: 8.005821505552756
native_rmse: 9.126912011951266
mae 提升: 10.52 %
rmse 提升: 12.28 %

************************
开始第5小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.316150503518251
native_mae: 6.385894428152493
lgb_model_rmse1: 8.32370085841098
native_rmse: 9.886455781415732
mae 提升: 16.75 %
rmse 提升: 15.81 %

************************
开始第6小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 6.493319605827357
native_mae: 8.143782991202345
lgb_model_rmse1: 13.359506448235226
native_rmse: 16.166565303871447
mae 提升: 20.27 %
rmse 提升: 17.36 %

************************
开始第7小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 9.33930485292105
native_mae: 13.43222873900293
lgb_model_rmse1: 41.86574862889937
native_rmse: 53.82472041326348
mae 提升: 30.47 %
rmse 提升: 22.22 %

************************
开始第8小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 9.481575799474124
native_mae: 13.457272727272729
lgb_model_rmse1: 42.06633930468275
native_rmse: 52.84917242587348
mae 提升: 29.54 %
rmse 提升: 20.4 %

************************
开始第9小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.876492238637579
native_mae: 7.555777126099707
lgb_model_rmse1: 13.033513079371941
native_rmse: 15.359643736704152
mae 提升: 22.23 %
rmse 提升: 15.14 %

************************
开始第10小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.387169302763995
native_mae: 6.381935483870967
lgb_model_rmse1: 8.258474085397973
native_rmse: 9.727253035307719
mae 提升: 15.59 %
rmse 提升: 15.1 %

************************
开始第11小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.317615258773102
native_mae: 6.143372434017596
lgb_model_rmse1: 7.659060329703839
native_rmse: 8.989072789713537
mae 提升: 13.44 %
rmse 提升: 14.8 %

************************
开始第12小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.282343193034275
native_mae: 6.110146627565983
lgb_model_rmse1: 7.130791010176201
native_rmse: 8.503378455725132
mae 提升: 13.55 %
rmse 提升: 16.14 %

************************
开始第13小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 5.8076585600781865
native_mae: 6.598709677419355
lgb_model_rmse1: 7.614335247014959
native_rmse: 9.052369725876144
mae 提升: 11.99 %
rmse 提升: 15.89 %

************************
开始第14小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 6.442634652147794
native_mae: 7.699384164222875
lgb_model_rmse1: 8.64435064626146
native_rmse: 10.497624099300054
mae 提升: 16.32 %
rmse 提升: 17.65 %

************************
开始第15小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 7.21275839705586
native_mae: 8.35041055718475
lgb_model_rmse1: 9.734510953976297
native_rmse: 11.630062534030268
mae 提升: 13.62 %
rmse 提升: 16.3 %

************************
开始第16小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 8.002575713560498
native_mae: 9.210322580645162
lgb_model_rmse1: 11.440854508747305
native_rmse: 13.024616733544157
mae 提升: 13.11 %
rmse 提升: 12.16 %

************************
开始第17小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 8.994822351884974
native_mae: 10.397126099706744
lgb_model_rmse1: 13.838375550826106
native_rmse: 15.118252819967184
mae 提升: 13.49 %
rmse 提升: 8.47 %

************************
开始第18小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 11.061113518839228
native_mae: 13.56565982404692
lgb_model_rmse1: 17.915247700810294
native_rmse: 21.0999382009074
mae 提升: 18.46 %
rmse 提升: 15.09 %

************************
开始第19小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 14.953595553994731
native_mae: 17.625219941348977
lgb_model_rmse1: 24.12044524748898
native_rmse: 28.14372975176133
mae 提升: 15.16 %
rmse 提升: 14.3 %

************************
开始第20小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 21.792515176428225
native_mae: 27.329794721407623
lgb_model_rmse1: 44.923622721070835
native_rmse: 56.21990567004171
mae 提升: 20.26 %
rmse 提升: 20.09 %

************************
开始第21小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 19.77119381426735
native_mae: 25.52944281524927
lgb_model_rmse1: 43.69556646665105
native_rmse: 54.60265172467881
mae 提升: 22.56 %
rmse 提升: 19.98 %

************************
开始第22小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 14.270870654935054
native_mae: 17.374780058651023
lgb_model_rmse1: 29.1681949041718
native_rmse: 33.8725738069162
mae 提升: 17.86 %
rmse 提升: 13.89 %

************************
开始第23小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 8.79874861081255
native_mae: 10.374721407624632
lgb_model_rmse1: 13.683615311752986
native_rmse: 15.52517869807102
mae 提升: 15.19 %
rmse 提升: 11.86 %

************************
开始第24小时预测
************************
(1431, 36)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 6.366542133017135
native_mae: 7.123958944281523
lgb_model_rmse1: 9.371555247149464
native_rmse: 10.39863975708621
mae 提升: 10.63 %
rmse 提升: 9.88 %

In [171]:
y_pred = preds
y_test = y_tests
xgb_model_mae1 = mean_absolute_error(y_test, y_pred)
xgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
print("lgb_model_mae1:", xgb_model_mae1)

print("lgb_model_rmse1:", xgb_model_rmse1)

lgb_model_mae1: 8.616168147749963
lgb_model_rmse1: 21.28036327731396

In [172]:
model1, X_test, y_test, dt = short_term_forecast_CAT()

y_pred = model1.predict(X_test)
lgb_model_mae1 = mean_absolute_error(y_test, y_pred)
lgb_model_rmse1 = np.sqrt(mean_squared_error(y_test, y_pred))
native_mae = mean_absolute_error(y_test, X_test['dam_lag_24h'])
native_rmse = np.sqrt(mean_squared_error(y_test, X_test['dam_lag_24h']))
print("lgb_model_mae1:", lgb_model_mae1)
print("native_mae:", native_mae)

print("lgb_model_rmse1:", lgb_model_rmse1)
print("native_rmse:", native_rmse)

lgb_mae_enhance1 = round((native_mae - lgb_model_mae1) / native_mae * 100, 2)
lgb_rmse_enhance1 = round((native_rmse - lgb_model_rmse1) / native_rmse * 100, 2)
print('mae 提升:', lgb_mae_enhance1, '%')
print('rmse 提升:', lgb_rmse_enhance1, '%')

(34340, 37)

Default metric period is 5 because MAE is/are not implemented for GPU

lgb_model_mae1: 8.575662316495931
native_mae: 10.578265705206551
lgb_model_rmse1: 21.223247015516
native_rmse: 26.220882300682653
mae 提升: 18.93 %
rmse 提升: 19.06 %

In [173]:
cat_pre = model1.predict(X_test)

## 最终结果

In [200]:
pre = xgb_pre + lgb_pre + cat_pre
pre = pre / 3

In [201]:
mean_absolute_error(y_test, pre)

8.54020795335717

In [202]:
np.sqrt(mean_squared_error(y_test, pre))

20.90615997789408

In [ ]:
xgb_mae = 8.61
xgb_rmse = 20.85

lgb_mae = 8.57
lgb_rmse = 20.81

cat_mae = 8.58
cat_rmse = 21.22

native_mae = 10.58
native_rmse = 26.22